//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rift.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rift.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файловая структура игрового клиента не прошла проверку. Переместите исполняемый файл в папку с игрой..
        /// </summary>
        internal static string ExceptionBadClient {
            get {
                return ResourceManager.GetString("ExceptionBadClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия Вашего игрового клиента ({0}) не поддерживается..
        /// </summary>
        internal static string ExceptionClientVersionFormat {
            get {
                return ResourceManager.GetString("ExceptionClientVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимые для запуска клиента файлы не найдены..
        /// </summary>
        internal static string ExceptionMissingExecutable {
            get {
                return ResourceManager.GetString("ExceptionMissingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка..
        /// </summary>
        internal static string ExceptionUnknown {
            get {
                return ResourceManager.GetString("ExceptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageAsmodians {
            get {
                object obj = ResourceManager.GetObject("ImageAsmodians", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageBackgroundL0 {
            get {
                object obj = ResourceManager.GetObject("ImageBackgroundL0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCommandButton {
            get {
                object obj = ResourceManager.GetObject("ImageCommandButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageElyos {
            get {
                object obj = ResourceManager.GetObject("ImageElyos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMessageDialog {
            get {
                object obj = ResourceManager.GetObject("ImageMessageDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteClose {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteDelete {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteForum {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteForum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteMinimize {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpritePlay {
            get {
                object obj = ResourceManager.GetObject("ImageSpritePlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteShop {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteShop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteSocial {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteSocial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteVote {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteVote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSpriteWebPage {
            get {
                object obj = ResourceManager.GetObject("ImageSpriteWebPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageUnknownItem {
            get {
                object obj = ResourceManager.GetObject("ImageUnknownItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - персонажа с таким именем не существует.
        /// </summary>
        internal static string ItemBoughtResultCharacter {
            get {
                return ResourceManager.GetString("ItemBoughtResultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - данный предмет недоступен для покупки.
        /// </summary>
        internal static string ItemBoughtResultId {
            get {
                return ResourceManager.GetString("ItemBoughtResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - недостаточно средств для покупки.
        /// </summary>
        internal static string ItemBoughtResultPoints {
            get {
                return ResourceManager.GetString("ItemBoughtResultPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - сервис покупок в данный момент недоступен.
        /// </summary>
        internal static string ItemBoughtResultService {
            get {
                return ResourceManager.GetString("ItemBoughtResultService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только для асмодиан.
        /// </summary>
        internal static string ItemRaceAsmo {
            get {
                return ResourceManager.GetString("ItemRaceAsmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только для элийцев.
        /// </summary>
        internal static string ItemRaceEly {
            get {
                return ResourceManager.GetString("ItemRaceEly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string MessageDialogError {
            get {
                return ResourceManager.GetString("MessageDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string MessageDialogInfo {
            get {
                return ResourceManager.GetString("MessageDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время работы произошла ошибка, кярун!.
        /// </summary>
        internal static string MessageDialogTitleError {
            get {
                return ResourceManager.GetString("MessageDialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание, нян-нян!.
        /// </summary>
        internal static string MessageDialogTitleWarning {
            get {
                return ResourceManager.GetString("MessageDialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string MessageDialogWarning {
            get {
                return ResourceManager.GetString("MessageDialogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няян! Через некоторое время заказ будет доставлен в игре персонажу {0}..
        /// </summary>
        internal static string MessageItemBoughtSuccessFormat {
            get {
                return ResourceManager.GetString("MessageItemBoughtSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.aiondatabase.net.
        /// </summary>
        internal static string NavigationDatabaseUri {
            get {
                return ResourceManager.GetString("NavigationDatabaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.atreiaworld.com.
        /// </summary>
        internal static string NavigationForumUri {
            get {
                return ResourceManager.GetString("NavigationForumUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aiondatabase.net/ru/item/{0}.
        /// </summary>
        internal static string NavigationItemFormat {
            get {
                return ResourceManager.GetString("NavigationItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tokatcc.1gb.ru/buy?user={0}&amp;password={1}&amp;item_id={2}&amp;count={3}&amp;character={4}.
        /// </summary>
        internal static string NavigationServerBuyUriFormat {
            get {
                return ResourceManager.GetString("NavigationServerBuyUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://atreiaworld.com/online.
        /// </summary>
        internal static string NavigationServerOnlineUri {
            get {
                return ResourceManager.GetString("NavigationServerOnlineUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tokatcc.1gb.ru/points?user={0}&amp;password={1}.
        /// </summary>
        internal static string NavigationServerPointsFormat {
            get {
                return ResourceManager.GetString("NavigationServerPointsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/aggpys/Atreia-World/master/Server%20Files/gshop-0.1.xml.
        /// </summary>
        internal static string NavigationServerPriceUri {
            get {
                return ResourceManager.GetString("NavigationServerPriceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tokatcc.1gb.ru/status.
        /// </summary>
        internal static string NavigationServerStatusUri {
            get {
                return ResourceManager.GetString("NavigationServerStatusUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vk.com/atreiaworld.
        /// </summary>
        internal static string NavigationSocialUri {
            get {
                return ResourceManager.GetString("NavigationSocialUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aion.mmo-top.ru.
        /// </summary>
        internal static string NavigationVoteUri {
            get {
                return ResourceManager.GetString("NavigationVoteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://atreiaworld.com.
        /// </summary>
        internal static string NavigationWebUri {
            get {
                return ResourceManager.GetString("NavigationWebUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка типа {0}..
        /// </summary>
        internal static string NotExceptionFormat {
            get {
                return ResourceManager.GetString("NotExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-zA-Z0-9а-яА-Я_].
        /// </summary>
        internal static string RegexCharacterName {
            get {
                return ResourceManager.GetString("RegexCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RiftIcon {
            get {
                object obj = ResourceManager.GetObject("RiftIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        internal static string ShopCategorySearch {
            get {
                return ResourceManager.GetString("ShopCategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtreiaWorld.com.
        /// </summary>
        internal static string TrayAppName {
            get {
                return ResourceManager.GetString("TrayAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База знаний.
        /// </summary>
        internal static string TrayMenuDatabase {
            get {
                return ResourceManager.GetString("TrayMenuDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум.
        /// </summary>
        internal static string TrayMenuForum {
            get {
                return ResourceManager.GetString("TrayMenuForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить процесс &apos;{0}&apos;.
        /// </summary>
        internal static string TrayMenuKillFormat {
            get {
                return ResourceManager.GetString("TrayMenuKillFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезные ресурсы.
        /// </summary>
        internal static string TrayMenuResources {
            get {
                return ResourceManager.GetString("TrayMenuResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скриншоты.
        /// </summary>
        internal static string TrayMenuScreenshots {
            get {
                return ResourceManager.GetString("TrayMenuScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string TrayMenuSeparator {
            get {
                return ResourceManager.GetString("TrayMenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа ВКонтакте.
        /// </summary>
        internal static string TrayMenuSocial {
            get {
                return ResourceManager.GetString("TrayMenuSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое окно....
        /// </summary>
        internal static string TrayMenuStart {
            get {
                return ResourceManager.GetString("TrayMenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосовать за проект.
        /// </summary>
        internal static string TrayMenuVote {
            get {
                return ResourceManager.GetString("TrayMenuVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-страница проекта.
        /// </summary>
        internal static string TrayMenuWeb {
            get {
                return ResourceManager.GetString("TrayMenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровой сервер в данный момент выключен или недоступен. Возможно, ведутся технические работы. Проверьте соединение с интернетом..
        /// </summary>
        internal static string WarningConnectionFailed {
            get {
                return ResourceManager.GetString("WarningConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный аккунт ранее уже был использован для входа в игру..
        /// </summary>
        internal static string WarningEntered {
            get {
                return ResourceManager.GetString("WarningEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось купить предмет:
        ///
        ///{0}.
        /// </summary>
        internal static string WarningItemBoughtFailureFormat {
            get {
                return ResourceManager.GetString("WarningItemBoughtFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин и/или пароль не были указаны. Введите корректные данные игрового аккаунта для того, чтобы продолжить....
        /// </summary>
        internal static string WarningLoginInfo {
            get {
                return ResourceManager.GetString("WarningLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить информацию о счёте аккаунта..
        /// </summary>
        internal static string WarningUpdatePointsCount {
            get {
                return ResourceManager.GetString("WarningUpdatePointsCount", resourceCulture);
            }
        }
    }
}
